import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const labrada = localFont({
  src: [
    {
      path: "../../public/fonts/Labrada-ExtraLight.woff2",
      style: "extra-light",
      weight: "100",
    },
    {
      path: "../../public/fonts/Labrada-Light.woff2",
      style: "light",
      weight: "300",
    },
    {
      path: "../../public/fonts/Labrada-LightItalic.woff2",
      style: "italic",
      weight: "300",
    },
    {
      path: "../../public/fonts/Labrada-Regular.woff2",
      style: "normal",
      weight: "400",
    },
    {
      path: "../../public/fonts/Labrada-Bold.woff2",
      style: "bold",
      weight: "600",
    },
  ],
  variable: "--font-labrada-regular",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${labrada.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
